export enum BillStatus {
  PAID_YESTERDAY = 'PAID_YESTERDAY',
  PAID_TODAY = 'PAID_TODAY',
  PAID = 'PAID',
  OVERDUE_YESTERDAY = 'OVERDUE_YESTERDAY',
  OVERDUE = 'OVERDUE',
  DUE_TODAY = 'DUE_TODAY',
  DUE_TOMORROW = 'DUE_TOMORROW',
  UPCOMING = 'UPCOMING',
}
