export enum AppErrorKey {
  AUTH_EMAIL_ALREADY_IN_USE = 'AUTH_EMAIL_ALREADY_IN_USE',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_CREDENTIAL = 'AUTH_INVALID_CREDENTIAL',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
}
